### PR TITLE
Commit messages convention; #trivial

### PR DESCRIPTION
**Pull request by Mourad-Aly**
That goal is to see conichi's history coming from one single man 🏈😀

### CODE REVIEW

**Comment by Antondomashnev** [comment]
@David-Henner @hossein1448 please review it.

**Comment by Antondomashnev** [comment]
@Mourad-Aly http://danger.systems/plugins/commit_lint.html 😄

**Comment by Mourad-Aly** [comment]
> @Mourad-Aly http://danger.systems/plugins/commit_lint.html 😄
👍 Cool, i'll create a PR for using it 😀

**Comment by Mourad-Aly** [comment]
Perfect 👍

**Pull request merged**
