### PR TITLE
changed names of scripts to explicitly call bash

### PR DESCRIPTION
**Pull request by wladyslaws**
rather than assuming recognition of them as executables. This pull request is based on assumption that when executing a script it does not have bootstrap_ruby.sh and bootstrap_projects.sh sourced in the .bash_profile and can't find them in current directory if they are called as executables.

### CODE REVIEW

**Comment by Antondomashnev** [comment]
@wladyslaws btw congratulations on your first PR
 <img

**Comment by wladyslaws** [comment]
In my case, using a new mac, when script bootstrap.sh calls others scripts as executables (i.e. just runs `bootstrap_ruby` instead of `bash bootstrap_ruby.sh`) bash does not recognise them (probably some default settings?) and throws 

> bootstrap_ruby: command not found

So I changed lines in the script to explicitly inform bash that we run `bootstrap_ruby.sh` and `bootstrap_projects.sh`.

@Antondomashnev I assumed we have scripts in the same folder, I'm not sure you mean by having different situation?

@Antondomashnev also I noticed that i get an error after the end of ruby installation script:

> bootstrap_ruby.sh: line 56: shell_session_update: command not found

And will have to pay attention to second script since everything stops after. So this pull should be rejected I think, my bad. This "session_update" may be somehow related to terminal app or so? Any ideas?

My motivation is to make this scripts run on a brand new mac that a new dev is going to receive, not a private one where everybody had adjusted environment to work in proper way.

**Comment by Antondomashnev** [comment]
> In my case, using a new mac, when script bootstrap.sh calls others scripts as executables (i.e. just runs bootstrap_ruby instead of bash bootstrap_ruby.sh) bash does not recognize them (probably some default settings?) and throws

That sounds reasonable I'd like to accept that PR and open another one for the `bootstrap_ruby.sh: line 56: shell_session_update: command not found` fix.

> My motivation is to make this scripts run on a brand new mac that a new dev is going to receive, not a private one where everybody had adjusted environment to work in proper way.
👍 that was the initial motivation when I wrote the script. The weird thing that it worked when I tested it before, anyway something may have been changed. 
Unfortunately these scripts can only be tested when a new mac comes, which is not an often case =(

**Comment by Antondomashnev** [comment]
@wladyslaws don't forget to remove branch 😉

**Pull request merged**
