### PR TITLE
Add script for adding and deleting guest/merchant app Lokalise key; #trivial

### PR DESCRIPTION
**Pull request by jotshin**
JIRA ticket: https://conichi.atlassian.net/browse/CNI-8185
**Please notice since this is a public repo, we provide the according credentials in JIRA**

## Description
The script allows you to:

1) Add and remove user input Lokalise key
2) Select whether guest or merchant app to action
3) Input default English value if it's add action

### CODE REVIEW

**Comment by David-Henner** [comment]
Thanks ! I'll submit a review after seeing a demo 😉

**Comment by ShengHuaWu** [comment]
@jotshin 

I will mark this PR as `trivial`.  
Could you please run a demo to show the result with us?

**Comment by jotshin** [comment]
I've updated the guide in `README` and put the needed credentials to 1Password ios-team value `Shell Credentials`.

**Comment by ShengHuaWu** [comment]
@jotshin 

I'm out of this review 😄  
One reviewer is enough for this PR. 
Thanks @David-Henner. 👍

**Pull request merged**
